trailingComma: 'es5'
printWidth: 140
singleQuote: true
arrowParens: 'avoid'
endOfLine: 'auto'
overrides:
  - files: '*.html'
    options:
      parser: 'html'
  - files: '*.component.html'
    options:
      parser: 'angular'
